### ISSUE TITLE
undefined method delete_prefix

### ISSUE THREAD

**Issue by mrbenas** [seattlerb/path_expander#8]
Hi! After the recent changes in b22384a and release of `1.1.2` our Flay checks have started failing:

```
~/path_expander-1.1.2/lib/path_expander.rb:58:in `block in expand_dirs_to_files': undefined method `delete_prefix' for #<Pathname:/test/test.rb> (NoMethodError)

    }.flatten.sort.map { |s| s.delete_prefix "./" }
                              ^^^^^^^^^^^^^^
        from ~/path_expander-1.1.2/lib/path_expander.rb:58:in `map'
        from ~/path_expander-1.1.2/lib/path_expander.rb:58:in `expand_dirs_to_files'
        from ~/path_expander-1.1.2/lib/path_expander.rb:113:in `block in process_args'
        from ~/path_expander-1.1.2/lib/path_expander.rb:95:in `each'
        from ~/path_expander-1.1.2/lib/path_expander.rb:95:in `process_args'
        from ~/path_expander-1.1.2/lib/path_expander.rb:147:in `process'
        from ~/flay-2.13.3/lib/flay.rb:26:in `run'
        from ~/pronto-flay-0.11.1/lib/pronto/flay.rb:25:in `flay'
        from ~/pronto-flay-0.11.1/lib/pronto/flay.rb:13:in `run'

```

It looks like the operation expects a `String`, but it's being passed a `Pathname`. Can it be fixed somehow?

**Comment by thayol** [comment]
Looks like the fix is already in `master`. (071a59131fc6fdda194ac1051339303547dc5c7e)
We just need a release and we're good to go!

**Comment by KieranP** [comment]
@zenspider Could we please have a release with the bug fix? Is there anything we can do to help with that process?

**Comment by emm26** [comment]
Hi! Could we have a release, please?

**Comment by KieranP** [comment]
@mrbenas @thayol @emm26 Looks like 1.1.3 was released which fixes this issue
